name: Documentation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, which is where the next step will look for it.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      # Build the documentation as HTML.
      - name: Build and Commit
        id: build
        uses: sphinx-notes/pages@v3
        with:
          publish: false
          documentation_path: "docs/"
          requirements_path: "./requirements.txt"

      # Publish built docs to gh-pages branch.
      - name: Push changes
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.build.outputs.artifact }}
